ajkaljdask

diff --git a/docker/docker-jenkins/Dockerfile b/docker/docker-jenkins/Dockerfile
--- a/docker/docker-jenkins/Dockerfile
+++ b/docker/docker-jenkins/Dockerfile
@@ -3,15 +3,27 @@ MAINTAINER Reed Palmer <reed.d.palmer@gmail.com>
 
 ENV JENKINS_UC http://updates.jenkins-ci.org
 
-# Add configuration for jenkins and plugins
-# RUN mkdir -p /var/jenkins_home
-
 # Install plugins from plugins.txt
 COPY plugins.txt /usr/share/jenkins/plugins.txt
 RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt
 
-# Add configuration files
-# ADD docker-jenkins-job-builder/* /var/jenkins_home
+RUN apt-get update && apt-get install -y\
+  python-setuptools \
+  python-dev \
+  libyaml-dev \
+  git \
+  curl \
+  python-pip \
+  python-yaml \
+  docker-engine 
 
-# Expose the jenkins dir as a volume
-# VOLUME /var/jenkins_home
+
+# RUN pip install jenkins-job-builder
+
+# RUN git clone https://github.com/rdpa/docker-jenkins-job-builder.git /jjb
+
+# CMD while ! curl --output /dev/null --silent --head --fail http://jenkins:8080/; \
+#  do sleep 1; echo -n .; done \
+#  && jenkins-jobs --conf /jjb/jenkins_jobs.ini update /jjb
+
+# VOLUME /jjb
